namespace GitHubCopilotTesting
{
    public class BubbleSort
    {
        /// <summary>
        /// Sorts the given array in ascending order using bubble sort algorithm.
        /// Generated by GitHub Copilot.
        /// </summary>
        /// <param name="array">The array to sort.</param>
        public static void Sort(int[] array)
        {
            int n = array.Length;
            for (int i = 0; i < n - 1; i++)
            {
                for (int j = 0; j < n - i - 1; j++)
                {
                    if (array[j] > array[j + 1])
                    {
                        // VS' suggestion: use tuple for swapping
                        (array[j + 1], array[j]) = (array[j], array[j + 1]);
                    }
                }
            }
        }
    }
}