namespace GitHubCopilotTesting;

public class InsertionSort
{
    /// <summary>
    /// Sorts the given array in ascending order using insertion sort algorithm.
    /// Generated by GitHub Copilot.
    /// </summary>
    public static void Sort(int[] array)
    {
        for (int i = 1; i < array.Length; i++)
        {
            int key = array[i];
            int j = i - 1;

            while (j >= 0 && array[j] > key)
            {
                array[j + 1] = array[j];
                j--;
            }

            array[j + 1] = key;
        }
    }
}
