namespace GitHubCopilotTesting;

public class QuickSort
{
    /// <summary>
    /// Sorts the array using the quick sort algorithm.
    /// Generated by GitHub Copilot.
    /// </summary>
    /// <param name="array">The array to sort.</param>
    public static void Sort(int[] array)
    {
        QuickSortArray(array, 0, array.Length - 1);
    }

    private static void QuickSortArray(int[] array, int low, int high)
    {
        if (low < high)
        {
            int pivotIndex = Partition(array, low, high);
            QuickSortArray(array, low, pivotIndex - 1);
            QuickSortArray(array, pivotIndex + 1, high);
        }
    }

    private static int Partition(int[] array, int low, int high)
    {
        // Select the pivot element as the last element of the array
        int pivot = array[high];
        int i = low - 1;

        // Iterate through the array from low to high-1
        for (int j = low; j < high; j++)
        {
            // If the current element is smaller than the pivot,
            // swap it with the element at index i+1 and increment i
            if (array[j] < pivot)
            {
                i++;
                Swap(array, i, j);
            }
        }

        // Swap the pivot element with the element at index i+1
        Swap(array, i + 1, high);
        return i + 1;
    }

    private static void Swap(int[] array, int a, int b)
    {
        // Swap the elements at indices a and b in the array
        (array[b], array[a]) = (array[a], array[b]);
    }
}

